### ISSUE TITLE
Skip Tls Verify with vault Option

### ISSUE THREAD

**Issue by thepnux** [nmaupu/vault-secret#12]
When i put key-value VAULT_SKIP_VERIFY=true in environment variable, it seems to be ignored
I tested this option in container with vault-vli successfully.

**Comment by IceBear2k** [comment]
Can confirm, it has no effect.

**Comment by nmaupu** [comment]
No indeed, you need to use the config `insecure` into the CR directly.
It would be a shame to skip all TLS requests if one's using multiple vaults, wouldn't it ? ;)
I updated the README to indicate that !
