### ISSUE TITLE
No linux/arm64 support

### ISSUE THREAD

**Issue by moikot** [nmaupu/vault-secret#25]
I'm running my bare-metal Kubernetes cluster on linux/arm64 platform and would love to use vault-secret CRD. Unfortunately the Docker image targets linux/amd64. Would it be possible to implement multi-arch support and include arm64? 

I made small [modifications in the Docker](https://github.com/moikot/vault-secret/commit/6ea30510b02ee3a3846651e595570baf69ea5ea3#diff-3254677a7917c6c01f55212f86c57fbf) file and implemented my build [using GitHub actions](https://github.com/moikot/vault-secret/blob/master/.github/workflows/main.yml) but CircleCI is used in this project and I guess multi-arch should be implemented using CricleCI's capabilities.

**Comment by nmaupu** [comment]
I guess this is entirely possible.

**Comment by nmaupu** [comment]
See #27

I like your nice approach 👍 However, circleci's docker daemon doesn't support BuildKit :/
As a result, I reverted to the old way of cross compiling go binaries...
Can you try the following image tag on your `arm64` cluster and tell me if this is working as expected ? `nmaupu/vault-secret:arch-arm64-linux-arm64`

Thanks !

**Comment by moikot** [comment]
@nmaupu Thanks for the image! I tested it on my ROCK64 SBC (which is linux/arm64) and I can confirm that it's running well.

**Comment by nmaupu** [comment]
I added the support for `linux/arm64` from version 1.1.2 (already available).
Tags are:
- `<version>-linux-amd64`
- `<version>-linux-arm64`
