### ISSUE TITLE
Release manifests contain CRD only

### ISSUE THREAD

**Issue by moikot** [nmaupu/vault-secret#26]
the README.md states:

Get the latest release from https://github.com/nmaupu/vault-secret/releases

Deploy the Custom Resource Definition and the operator:
```shell
$ kubectl apply -f deploy/crds/maupu_v1beta1_vaultsecret_crd.yaml
$ kubectl apply -f deploy/service_account.yaml
$ kubectl apply -f deploy/role.yaml
$ kubectl apply -f deploy/role_binding.yaml
$ kubectl apply -f deploy/operator.yaml
```

But the latest two releases contains  maupu.org_vaultsecrets.yaml only

**Comment by nmaupu** [comment]
Hi,

It's due to operator-sdk which now uses kustomize as deployment yaml.
As a result, I decided not to include them anymore. Will see in the future if I make some compatible yaml. The README is outdated though 🙄

**Comment by nmaupu** [comment]
See #28
