### ISSUE TITLE
Add service account namespace in kubernetes auth

### ISSUE THREAD

**Issue by Codenxp** [nmaupu/vault-secret#30]
Hi,
We have the requirement to use one service account to auth with Vault and use it for all the namespaces in one cluster.  I updated the `KubernetesAuthType` with adding one argument: `serviceAccountNamespace`. 
With this update, user could choose using centralized service account or specified service account in the same namespace with VaultSecret.
I have test this update in my local and confirmed it works well. I have no permission to push new branch to this repo. It would be much helpful for both of you and others to evaluate this update if you could give me permission to push new branch. Could you kindly help to consider this request? Thank you.

**Comment by nmaupu** [comment]
Hi, that's not how it works, could you not just issue a PR instead so I can review your proposal?

**Comment by Codenxp** [comment]
But I have no permission to push my branch to this repo: 
`remote: Permission to nmaupu/vault-secret.git denied to Codenxp. `
For api/v1beta1/vaultsecret_types.go
```
type KubernetesAuthType struct {
	Role    string `json:"role,required"`
	Cluster string `json:"cluster,required"`
	// ServiceAccount to use for authentication, using "default" if not provided
	ServiceAccount string `json:"serviceAccount,omitempty"`
	ServiceAccountNamespace string `json:"serviceAccountNamespace,omitempty"`
}
```
For api/v1beta1/utils.go
```
                // Retrieving token from the serviceAccount configured
		saName := cr.Spec.Config.Auth.Kubernetes.ServiceAccount
		if saName == "" {
			saName = "default"
		}
		// Retrieving the namespace of serviceAccount from configuration
		saNamespace := cr.Spec.Config.Auth.Kubernetes.ServiceAccountNamespace
		if saNamespace == "" {
			saNamespace = cr.Namespace
		}
		tok, err := k8sutils.GetTokenFromSA(c, saNamespace, saName)
		if err != nil {
			return nil, err
		}
```

**Comment by nmaupu** [comment]
Hi, you need to fork, change, push and issue a PR. You don't seem very familiar with git so you should read some doc beforehand I'm afraid.

**Comment by Codenxp** [comment]
Hi,
PR is created: https://github.com/nmaupu/vault-secret/pull/31. Please help to have a review. Thank you.

**Comment by primeroz** [comment]
I do have a similar requirement where i need the `same` serviceaccount from many namespace to pull secrets for `dockerconfigjson secrets` 

I solved it by
* using the same , in my case `deafult`, serviceaccount in every namespace
* Create a policy and a role on vault to allow `serviceaccount_name=default` `serviceaccount_namespaces=*` to grab the needed secrets 

create the `VaultSecret` resource in every namespace with the same spec.

Would that work for you without the change ?
