### ISSUE TITLE
How to proceed with deprecated apiextensions.k8s.io/v1beta1 for crd ?

### ISSUE THREAD

**Issue by primeroz** [nmaupu/vault-secret#32]
Hi,

I was wondering what the plan is going forward with the deprecated `apiextensions.k8s.io/v1beta1`. This was supposed to be removed in `1.19` but has been postponed to `1.22` which give us more time to address the issue. 

Also given the fact that 1.16 is EOL maybe is time to think about it ? 

I have testied the vault-secret operator on 1.20 and the operator is working as expected. Secrets are created with no issue

```
$ kubectl apply -f https://raw.githubusercontent.com/nmaupu/vault-secret/master/config/crd/bases/maupu.org_vaultsecrets.yaml --dry-run=client

Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
customresourcedefinition.apiextensions.k8s.io/vaultsecrets.maupu.org created (dry run)
```

the version is returned as v1 from the apiserver both on 1.20 and 1.17 so maybe we can just move the CRD spec and code to v1 rather than v1beta1 and deprecate older version of the code ?

```
$ kubectl get crd vaultsecrets.maupu.org -o yaml | grep apiVersion | egrep -v "\   {"
apiVersion: apiextensions.k8s.io/v1
  - apiVersion: apiextensions.k8s.io/v1
  - apiVersion: apiextensions.k8s.io/v1beta1
              f:apiVersion:
          apiVersion:
```

I can totally try getting this as a PR but wanted to check what your thoughts are first about moving 

Thanks for the tool though!

**Comment by nmaupu** [comment]
Hi,

Thanks for the detail review. I totally agree, this has to be addressed. As for how to do it, I didn't look at it too much yet...
Nervertheless, I remarked that my clusters which are running k8s 1.18, updated CRDs to `apiextensions.k8s.io/v1` automatically. This is probably due to a webhook or something, I need to investigate this though.

The main concern would be that older versions of k8s (<1.16) don't support `apiextensions.k8s.io/v1`. Perhaps Operator SDK addressed that as well but I am not quite sure... Maybe this PR is related to this point:

https://github.com/operator-framework/operator-sdk/pull/2684

If you have time to check on this, I will be more than happy to review a PR in that regard 👍

**Comment by nmaupu** [comment]
Thanks to @vflaux for the code digging:

`apiextensions` apigroup declaration is here:
https://github.com/kubernetes/apiextensions-apiserver/tree/master/pkg/apis/apiextensions
Conversions are done using this code:
https://github.com/kubernetes/apiextensions-apiserver/blob/master/pkg/apis/apiextensions/v1beta1/conversion.go

That is why, existing CRDs are updated _magically_.
As per https://kubernetes.io/docs/reference/using-api/deprecation-guide/#customresourcedefinition-v122, manifests have to be migrated ofc.

**Comment by primeroz** [comment]
Nice, i ll have a look as soon as i have time  ( knowing i can wait for 1.22 made this way less urgent ! ) 

what i am not sure about, but is a good chance to learn, is https://github.com/nmaupu/vault-secret/tree/master/api/v1beta1 and the auto-generated code. I guess we will need to update all of this as well and not rely on the auto conversion and compatiblity layer from apiserver.

**Comment by sadovnikov** [comment]
@nmaupu, @gdlx Thank you very much for upgrading the CRD definitions. Although the new version of the Operator is not released yet, we tried to use the changed CRD. The operator manages to update the secrets but then logs errors, which seem to occur at attempts to update the VaultSecret status.

```
2022-02-22T12:46:47.686Z     ERROR  controller     Reconciler error      {"reconcilerGroup": "maupu.org", "reconcilerKind": "VaultSecret", "controller": "vaultsecret", "name": "git-github", "namespace": "argocd", "error": "vaultsecrets.maupu.org \"git-github\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
       /go/pkg/mod/github.com/go-logr/[zapr@v0.1.0](mailto:zapr@v0.1.0)/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
       /go/pkg/mod/sigs.k8s.io/[controller-runtime@v0.6.2](mailto:controller-runtime@v0.6.2)/pkg/internal/controller/controller.go:237
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
       /go/pkg/mod/sigs.k8s.io/[controller-runtime@v0.6.2](mailto:controller-runtime@v0.6.2)/pkg/internal/controller/controller.go:209
``` 

Are you planning to make a new release?

**Comment by nmaupu** [comment]
hi! I can do that next week, not sure it will solve your issue though...
