### ISSUE TITLE
Release with updated CRDs

### ISSUE THREAD

**Issue by sadovnikov** [nmaupu/vault-secret#37]
Thank you very much for upgrading the CRD definitions with #32. Although the new version of the Operator is not released yet, we tried to use the changed CRD from https://github.com/nmaupu/vault-secret/blob/master/config/crd/bases/maupu.org_vaultsecrets.yaml. 

The operator manages to update the secrets but then logs errors, which seem to occur at attempts to update the VaultSecret status. Example is below

```
2022-02-22T12:46:47.686Z     ERROR  controller     Reconciler error      {"reconcilerGroup": "maupu.org", "reconcilerKind": "VaultSecret", "controller": "vaultsecret", "name": "git-github", "namespace": "argocd", "error": "vaultsecrets.maupu.org \"git-github\" not found"}
github.com/go-logr/zapr.(*zapLogger).Error
       /go/pkg/mod/github.com/go-logr/[zapr@v0.1.0](mailto:zapr@v0.1.0)/zapr.go:128
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
       /go/pkg/mod/sigs.k8s.io/[controller-runtime@v0.6.2](mailto:controller-runtime@v0.6.2)/pkg/internal/controller/controller.go:237
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
       /go/pkg/mod/sigs.k8s.io/[controller-runtime@v0.6.2](mailto:controller-runtime@v0.6.2)/pkg/internal/controller/controller.go:209
``` 

Would it be possible to release the new version of the Operator?

**Comment by nmaupu** [comment]
Hi, I can do that next week, not sure it will resolve your issue though!

**Comment by nmaupu** [comment]
Here you go:
https://github.com/nmaupu/vault-secret/releases/tag/1.2.0

**Comment by sadovnikov** [comment]
@nmaupu I'm afraid yesterday you accidentally reverted the CRDs back to `v1beta1`.
https://github.com/nmaupu/vault-secret/commit/88d788d46e77594243cb2e68dd08aea5a7dd0bec

![image](https://user-images.githubusercontent.com/4749332/157403569-4dc233c7-f17b-4d75-bbae-5f527defe45d.png)

**Comment by nmaupu** [comment]
Sh*t, I regenerated the crd with a recent operator sdk though 🤔. I'll check that today...

**Comment by nmaupu** [comment]
Fixed!
https://github.com/nmaupu/vault-secret/releases/tag/1.2.1

**Comment by sadovnikov** [comment]
Thank you! I'll give it a spin tomorrow morning

**Comment by sadovnikov** [comment]
The updated CRDs fail to apply

```
❯ kubectl apply -f maupu_v1beta1_vaultsecret_crd.yaml
* spec.validation.openAPIV3Schema.properties[spec].properties[secrets].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
* spec.validation.openAPIV3Schema.properties[status].properties[entries].items.x-kubernetes-map-type: Invalid value: "null": must be atomic as item of a list with x-kubernetes-list-type=set
```

According to https://www.pulumi.com/registry/packages/kubernetes/api-docs/apiextensions/v1beta1/customresourcedefinition/#x_kubernetes_list_type_nodejs, the `x-kubernetes-list-type` defaults to `atomic`. That's how I changed CRDs in order to get them applied. 

Alternatively, the lists' values should be annotated with `x-kubernetes-map-type: atomic`

**Comment by primeroz** [comment]
I confirm the same issue with the CRD , switching those values to atomic

**Comment by eugenebnd** [comment]
I've created PR #39
