### ISSUE TITLE
Secret type support

### ISSUE THREAD

**Issue by mool** [nmaupu/vault-secret#9]
It would be great to be able to specify the secret type, for example to be able to set it to `kubernetes.io/dockerconfigjson` for storing the credentials for private docker registries.

**Comment by nmaupu** [comment]
Hi,

Good point ! I'll see what I can do when I have spare time.
In the meantime, feel free to make a PR for this !

**Comment by nmaupu** [comment]
Thanks for the PR, it has been merged and release 0.0.11 includes it !
